name: Crate BM digital contacts 

on:
  schedule:
      - cron: '0 22 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Requirements
        run: pip3 install -r requirements.txt

      - name: Generate BM digital contacts for whole world
        run: |
          python3 brandmeister-digital-contacts.py World


      - name: Generate BM digital contacts for Ukraine
        run: |
          python3 brandmeister-digital-contacts.py Ukraine


      - name: Generate BM digital contacts for RB 
        run: |
          python3 brandmeister-digital-contacts.py Belarus
      
      - name: Remove all CSV files which older then 15 mins
        run: find . -mmin +15 -name '*.csv' -exec rm {} \;

      - name: Create directory listing 
        run: tree -P "*.csv" -H '.' --charset utf-8 > index.html
               
      - name: setup git config
        run: |
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.EMAIL }}

      - name: Run a multi-line script
        run: |
          dated=`date +%Y-%m-%d-%H%M%S`
          git add .
          git commit -m "Brandmaister digital contacts on "${dated}
          git push -u origin main

